apiVersion: batch/v1
kind: CronJob
metadata:
  name: agentk-scheduler
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scheduler
            image: agent-k/client:v1
            # command: ["python", "-m", "src.main"]
            command: ["/app/entrypoint.sh"]
            volumeMounts:
              - name: agent-k
                mountPath: /app/
              - name: yaml-files
                mountPath: /app/test_samples
          restartPolicy: Never
          volumes: 
          - name: agent-k
            hostPath:
              path: /run/desktop/mnt/host/c/Users/vinio/facul/AgentK/client
              type: Directory
          - name: yaml-files
            hostPath:
              path: /run/desktop/mnt/host/c/Users/vinio/facul/test_samples
              type: Directory